# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kyRkG8mcBSriAM4juQgoyUfLKE2CPnmVIFZLqLgLZnvibgXtGGnIgUjE03bFxltsN1Z3AUBqB+PmZI4v8V28FxyJQxrJO9SW7+cKcHENc/AvhctPPR+v/tBDic+/t/non3cLM4dCUIGwrUwEQX7gBhW//f7nZbZaBwqB/NI5pTYECUlxzHH2HkL+jfpZNbJfqJLP6orSRzY7p8H+ssfi4UcAgLYMRZngHznf7o6aHxIaQZjacT0UFxlaErvRckwe6lDuKwzRlP+iEDdb1hWijxbMtArBExwaJip5+yIsKDe1zNPhOsZg7m4fHF5rW98gTc5WyGtvF/c0am1FgF4QUAyeKiDFyCZq3NDq8925x+YAu6K+ap1cm1nlsEC4KDjLiTMQDEae6p2WCtQzB53o56nHmGolS2mripWPOdlPu8Y11uaMoF4tKX+u1fG1EQpPmIZjvpFmwouxXNm9N6IbGp3jF09XvVf1/16H0gAFcMZTrnv1NcPXRhISaxdRdG9rc67HyR+H0PfHcdmSB9KCacsCtrwfv+Ggv5yrE8WsJ+SyJb30FFlleyA0yZXKstCkR57TypBtCos2Q0XiFWrsI251rMYam4gDGkH6ol5J/y2XwfrLstp1b3oX6vW4cbrsS3Z7Jwq4IujhMnaT0S8y5zDheV4TcN5nuXbTOQoSrbI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
