travis:
  secure:
    BINSTAR_TOKEN: MTGfn7MjLX0hoos0V9zyQiDPru6zkGjnfrIH+ChO5bHwe7AcmxYwynAO4+3fb66SWlK3hhjG2xwh4jBcHOsnO+DdjxIuGb3ZW3Ps1Ge+8r6nxzl1yO8GNaiQuwL4pEzNygdpMmkHVA4ZQNnyLRlOUyOWKWBMSJjRSKi8YMEHLVxo2Y9yHXc3gmB2GnjyH/qTy5wsooz6zZK2mGN3xeU0jIjnIviDmFiVlq1T0gqobNZRhsyveoGQnmGcFcrAizbRvH4dly48Tj1+QrqvzeIEsCPcTd1WIEoum36Ni+mieLZ8yRCtEnU/Txui3rj1C3aeFBdEqghQUgBQGXmP+lxWVop65bicq5WKuInRxo/aeHztoWJfeP2b2u7sAt6m7kqS/yDLYGQlZjF+hbL8CsB8gPX1qprfdxNXFCOarlen3G2s8BOjy6NSkP0st0v3iK6OJuS0wNf83eiHqZOJ11xTsmXiikzEZdWIFKjbNvwKm9itCC7IBgqJbRBZblrp6vzgQ/v8nvoAKpiHxnMfP7v0gt9jD9a9lj/lDfiiA8ej2uwhjkreDIFSRKozIHxdeXGcl1O+EZx1kiJviVc7fBigiW8smH+bwMP0+f9TR0M0sifBRzZam5CMS3sh8WxxEjSeRzX43Oyx6umM9jicSD6/fZz7HTJsmTWu4XSG4Ftikpo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
