travis:
  secure:
    BINSTAR_TOKEN: kyRkG8mcBSriAM4juQgoyUfLKE2CPnmVIFZLqLgLZnvibgXtGGnIgUjE03bFxltsN1Z3AUBqB+PmZI4v8V28FxyJQxrJO9SW7+cKcHENc/AvhctPPR+v/tBDic+/t/non3cLM4dCUIGwrUwEQX7gBhW//f7nZbZaBwqB/NI5pTYECUlxzHH2HkL+jfpZNbJfqJLP6orSRzY7p8H+ssfi4UcAgLYMRZngHznf7o6aHxIaQZjacT0UFxlaErvRckwe6lDuKwzRlP+iEDdb1hWijxbMtArBExwaJip5+yIsKDe1zNPhOsZg7m4fHF5rW98gTc5WyGtvF/c0am1FgF4QUAyeKiDFyCZq3NDq8925x+YAu6K+ap1cm1nlsEC4KDjLiTMQDEae6p2WCtQzB53o56nHmGolS2mripWPOdlPu8Y11uaMoF4tKX+u1fG1EQpPmIZjvpFmwouxXNm9N6IbGp3jF09XvVf1/16H0gAFcMZTrnv1NcPXRhISaxdRdG9rc67HyR+H0PfHcdmSB9KCacsCtrwfv+Ggv5yrE8WsJ+SyJb30FFlleyA0yZXKstCkR57TypBtCos2Q0XiFWrsI251rMYam4gDGkH6ol5J/y2XwfrLstp1b3oX6vW4cbrsS3Z7Jwq4IujhMnaT0S8y5zDheV4TcN5nuXbTOQoSrbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
